[workspace]
resolver = "2"
members = ["crates/jilebi", "crates/jilebi_types", "crates/plugin-runtime"]

[workspace.dependencies]
tokio = { version = "1.44.1", features = ["full"] }
strum = "0.27.1"
strum_macros = "0.27.1"
derive_more = { version = "2.0.1", features = ["full"] }
serde = "1.0.219"
serde_json = "1.0.140"
toml = "0.8.20"
log = "0.4.27"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", rev = "a66f66ae345a0fafde1e2ee496ec137d77aef82a", features = [
	"server",
	"transport-io",
	"transport-sse-server",
	"transport-streamable-http-server",
] }
either = { version = "1.15.0", features = ["serde"] }

[patch.crates-io]
deno_media_type = { git = 'https://github.com/denoland/deno_media_type', tag = "0.2.6" }
